### ISSUE TITLE
Stream fails to open

### ISSUE THREAD

**Issue by vStone** [bromix/plugin.audio.soundcloud#27]
```
15:26:32 T:3592   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.audio.soundcloud/stream/)
15:26:32 T:3592   DEBUG:   ParentPath = [plugin://plugin.audio.soundcloud/]
15:26:32 T:6804   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin SoundCloud('plugin://plugin.audio.soundcloud/stream/','2','')
15:26:32 T:6804   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult - waiting on the SoundCloud (id=9) plugin...
15:26:32 T:3400  NOTICE: Thread LanguageInvoker start, auto delete: false
15:26:32 T:3400    INFO: initializing python engine.
15:26:32 T:3400   DEBUG: CPythonInvoker(9, C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\addon.py): start processing
15:26:32 T:3400  NOTICE: -->Python Interpreter Initialized<--
15:26:32 T:3400   DEBUG: CPythonInvoker(9, C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\addon.py): the source file to load is "C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\addon.py"
15:26:32 T:3400   DEBUG: CPythonInvoker(9, C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\addon.py): setting the Python path to C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
15:26:32 T:3400   DEBUG: CPythonInvoker(9, C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\addon.py): entering source directory C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud
15:26:32 T:3400   DEBUG: CPythonInvoker(9, C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\addon.py): instantiating addon using automatically obtained id of "plugin.audio.soundcloud" dependent on version 2.14.0 of the xbmc.python api
15:26:32 T:3400   DEBUG: [plugin.audio.soundcloud] Starting Nightcrawler by bromix...
15:26:32 T:3400  NOTICE: [plugin.audio.soundcloud] Running: SoundCloud (2.0.0) on Isengard (15.1) with Python (2.7.8)
15:26:32 T:3400   DEBUG: [plugin.audio.soundcloud] Path: "/stream/"
15:26:32 T:3400   DEBUG: [plugin.audio.soundcloud] Params: "{}"
15:26:32 T:3400   DEBUG: [plugin.audio.soundcloud] Setting content-type: "songs" for "/stream/"
15:26:33 T:3592   DEBUG: ------ Window Init (DialogBusy.xml) ------
15:26:33 T:3592    INFO: XCURL::DllLibCurlGlobal::CheckIdle - Closing session to http://raw.github.com (easy=0AC6C790, multi=0A4307A8)
15:26:33 T:3592    INFO: XCURL::DllLibCurlGlobal::CheckIdle - Closing session to http://mirrors.kodi.tv (easy=0AEB3B90, multi=0A8A3618)
15:26:33 T:3592   DEBUG: Joystick 0 button 1 Up
15:26:34 T:3400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\addon.py", line 6, in <module>
                                                nightcrawler.run(content.Provider())
                                              File "C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\resources\lib\nightcrawler\core\runner.py", line 47, in run
                                                result = provider.navigate(context)
                                              File "C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\resources\lib\nightcrawler\provider.py", line 174, in navigate
                                                result = method(context)
                                              File "C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\resources\lib\nightcrawler\core\nightcrawler_decorators.py", line 44, in wrapper
                                                return func(*args, **kwargs)
                                              File "C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\resources\lib\nightcrawler\core\nightcrawler_decorators.py", line 126, in wrapper
                                                return func(*args, **kwargs)
                                              File "C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\resources\lib\nightcrawler\core\nightcrawler_decorators.py", line 126, in wrapper
                                                return func(*args, **kwargs)
                                              File "C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\resources\lib\content\provider.py", line 481, in on_stream
                                                page_cursor=cursor)
                                              File "C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\resources\lib\nightcrawler\core\abstract_context.py", line 145, in cache_function
                                                return self.get_function_cache().get(seconds, func, *args, **keywords)
                                              File "C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\resources\lib\nightcrawler\storage\function_cache.py", line 107, in get
                                                cached_data = partial_func()
                                              File "C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\resources\lib\content\client.py", line 252, in get_stream
                                                return items.convert_to_items(response.json())
                                              File "C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\resources\lib\content\items.py", line 129, in convert_to_items
                                                item = convert_to_item(item)
                                              File "C:\Users\jan\AppData\Roaming\Kodi\addons\plugin.audio.soundcloud\resources\lib\content\items.py", line 84, in convert_to_item
                                                kind = json_item.get('kind', '')
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
15:26:34 T:3400    INFO: Python script stopped
```

**Comment by bromix** [comment]
Please a complete debug log via pastebin.com or similar...this is quite hard to read for me ;)

**Comment by vStone** [comment]
This log doesnt seem to be related to the issue :) 

I added some debug statements around the json_item in resources\lib\content\items.py and it looks like a ```None``` is apparently passed through.

I compared to the json I got from soundcloud and it seems to relate to this item:

```json
               {
			"origin": null,
			"tags": null,
			"created_at": "2015/08/16 08:17:21 +0000",
			"type": "track-repost"
		},
```

I modified the items.py a bit and this seems to resolve the issue for me
```python
def convert_to_item(json_item):
    if json_item is None:
        return None


```

**Comment by vStone** [comment]
Also, I'm of course willing to _mail_ you the json I received from soundcloud and the kodi log.

**Comment by bromix** [comment]
I see...the problem with that solution would be - the convert method throws an exception at the end, ergo expects a json_item and can not be None.
So the question is, why is the json_item **None**

Can you provide me with the complete result...this snippet doesn't help ;)

**Comment by vStone** [comment]
Apparently, github didnt think it was needed to mail my about new replies, sorry. 

I'm trying to find out where to put a debug statement that will put the json in a text file, maybe you can give me a pointer on this one.

**Comment by vStone** [comment]
http://paste2.org/8pzP870k

**Comment by bromix** [comment]
Found it...thanks for the data...was a lot of help :) somehow SoundCloud returns an incomplete item (don't know why). I skip these items. It seems you're the only one with this bug :)

Thanks for the help.
